spring.application.name=Libora Backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/libora
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT
app.jwt.secret=icwuwDwPApEsE3mEbeIksq+MFvrn5oE/zmtgpQKE7Yg=
app.jwt.expiration=86400000

# =========================
# EMAIL CONFIGURATION
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=naveenrajapaksha.info@gmail.com
spring.mail.password=qaul axqy vbvd zxdy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true